# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Py3.10"
            python: "3.10"
            toxenv: "py310-test"
            os: ubuntu-latest
          - name: "Py3.12"
            python: "3.12"
            toxenv: "py312-test"
            os: ubuntu-latest
          - name: "Py3.14"
            python: "3.14"
            toxenv: "py314-test"
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        init-shell: bash
        # only install micromamba; tox-conda will create its own envs
    - name: Show micromamba info and install tooling
      shell: bash -leo pipefail {0}
      run: |
        micromamba info
        micromamba list
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-astropy tox-conda
    - name: Lint with flake8
      shell: bash -leo pipefail {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Clean tox environment directory
      shell: bash -leo pipefail {0}
      run: |
        rm -rf .tox/${{ matrix.toxenv }}

    - name: Test with pytest
      shell: bash -leo pipefail {0}
      env:
        # make tox-conda use micromamba for environment creation
        CONDA_EXE: micromamba
        # tox creates the env directory (and log subdir) before micromamba;
        # allow micromamba to create into that existing, non-empty prefix
        MAMBA_ALLOW_EXISTING_PREFIX: "true"
      run: |
        tox -e ${{ matrix.toxenv }}
