# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Py3.10"
            python: "3.10"
            os: ubuntu-latest
          - name: "Py3.12"
            python: "3.12"
            os: ubuntu-latest
          - name: "Py3.14"
            python: "3.14"
            os: ubuntu-latest


    steps:
    - uses: actions/checkout@v3

    - name: Set up micromamba env (Python ${{ matrix.python }})
      uses: mamba-org/setup-micromamba@v2
      with:
        init-shell: bash
        environment-name: test-env
        condarc: |
          channels:
            - https://heasarc.gsfc.nasa.gov/FTP/software/conda/
            - conda-forge
          channel_priority: strict
        create-args: >-
          python=${{ matrix.python }}
          pip
          pytest
          pytest-astropy
          flake8
          # heasoft

    - name: Install package into micromamba env
      shell: bash -leo pipefail {0}
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Lint with flake8
      shell: bash -leo pipefail {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest (package + docs)
      shell: bash -leo pipefail {0}
      run: |
        pytest --pyargs heasarc_retrieve_pipeline docs --remote-data
